springdoc:
  api-docs:
    enabled: true
#  swagger-ui:  ##配置后返回404
#    path: /swagger-ui.html
#    title: AiDi
#    version: 1.0.0

play-items:
  items:
    item1: "手工 39.9"
    item2: "弹珠机 49.9"
    item3: "挖机寻 59.9"






